apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: secure-notes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: secure-notes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: secure-notes
