apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: secure-notes
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
  
    spec:
      serviceAccountName: mysql-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 999                 # Official MySQL Docker user ID
        runAsGroup: 999
        fsGroup: 999
      
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: tmp-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}

      containers:
      - name: mysql
        image: mysql:8.0
        securityContext: 
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: tmp-volume
              mountPath: /tmp
            - name: run-volume
              mountPath: /var/run/mysqld
          
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_NAME
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: initdb
        configMap:
          name: mysql-initdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: secure-notes
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  # SECURITY: ClusterIP ensures the database is not exposed outside the cluster network.
  type: ClusterIP
